spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080

logging:
  level:
    root: WARN
    com.mipt.mvpmts2: INFO

app:
  environment: production
  debug-mode: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskdb}
    username: ${DB_USER:taskuser}
    password: ${DB_PASSWORD:taskpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
