server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    user:
      password: '{bcrypt}$2a$10$xyz'

gateway:
  security:
    jwt:
      secret: "dGhpcy1pcy1hLXZlcnktc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLWp3dC1zaWduYXR1cmUtZ2VuZXJhdGlvbi1tdHMtc2VtMg=="
      expirationMs: 3600000
    password:
      pepper: "mts-pepper"
  external-api:
    base-url: "http://localhost:8080/external/v1"
    connect-timeout-ms: 2000
    read-timeout-ms: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
  ratelimiter:
    instances:
      externalApi:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
