spring:
  config:
    activate:
      on-profile: test

server:
  port: 0

logging:
  level:
    root: WARN
    com.mipt.mvpmts2: WARN

app:
  name: Task Manager MVP Test
  version: 1.0.0-test
  environment: test
  debug-mode: false
  load-default-tasks: false
  attachments:
    upload-dir: target/test-uploads

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
