spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG
    com.mipt.mvpmts2: DEBUG
    org.springframework.web: INFO

app:
  environment: development
  debug-mode: true

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskuser
    password: taskpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
